const B64 = `AAAAAOgD//8AAAAACAAAAAAAAAAAAACxu8/Mycy7AM7DvcW/zrIAAAAAAAAAAAAAAAAAAAAAAAAAAAC/7Nfc1eLb2QC91ebYAKOhoaUAwLvGxgAAAAAAAAAAAAAAAMHjAOjjAOjc2QDn2dfj4tgA2uDj4+YA49oA6NzZAMrJxRvHycgAAAC9v8jOv8wA1eLYAOHZ2egA6NzZANjZ4N3q2ebtAOTZ5ufj4gDd4gAA2+bZ2eKtAMzZ19nd6tkA6NzZALvPzMnMuwDOw73Fv84A1eLYAAAAAOjc2eIA59Xq2QDo3NkA29Xh2aurAAAAAAAAAAAAAAAAAAAAAAAAAAC+4wDi4+gA6OPn5wDo3N3nAL/s19zV4tvZAL3V5tgAAAAAAAAAAAAA1tna4+bZAObZ19nd6t3i2wDo3NkAu8/Mycy7AM7DvcW/zqurAAAAAAAAAAAAADP///+4KCcBCGpaK6cCuwGMJwEIK+QCuwGMJwEIR3MBAQAhDYABALsBjCcBCL2VJwEIZm1GcwEBACENgAAAuwGDJwEIGgCAcwEaAYABAAkAKUsIKacCvfInAQhmbWwCvYQoAQhmbWwCvVcoAQhmbWwCztzV4t8A7ePpANrj5gDp593i2wDo3NkAx9PNzr/M0/7Bw8DOAM3t5+jZ4a370+PpAOHp5+gA1tkA/QGt/s7c2ebZAN3nANUA6N3X39noANzZ5tkA2uPmAO3j6a3/w+gA1eTk2dXm5wDo4wDW2QDa4+YA6efZANXoAOjc2f7Qv8zHw8bDycgAvcPO0wDk4+borfvR3O0A4uPoANvd6tkA3egA1QDo5u0A1eLYAOfZ2QDr3NXo/t3oAN3nANXW4+norP/O3NXi3wDt4+kA2uPmAOnn3eLbAOjc2QDH083Ov8zT/sHDwM4Aze3n6Nnhrf/J3LgAw7ThAOfj5ubtuAD9Aa0A0+Pp5gC8u8G05/7Fv9MAw86/x80Aysm9xb/OAN3nANrp4OCt+8rg2dXn2QDn6OPm2QDn4+HZ6Nzd4tsA4+IA7ePp5gDKvbj+6NzZ4gDX4+HZANbV198A2uPmAOjc3eet/wIAAgD//wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAN02AAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAEFVUk8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQAAEQEAABAAAAAQAAABEAAAABEQAAAQAAAAEAAAAAEBAAEBAQAAABABAAEAAQABAAAQAAAQEAAAEBAAABAAAQEBAAEBAQAAAAEBERARAAAAAQAAAAEAAAAAAREQEAABAQAAAQEBEREQEAAAABAAAQAAAAEAAAAAEAEBEAAAAAEBAAABAQAAEAABAQAAABAAEAAAAQAAAAAAEAAAAAAAAQEAAQEBAREREBABAAABAQEAAQEAABARAAAQEQAAEAABAQAAAREAABEAAREQABAAEBARAAAQABAAEAABEAAAAAEBAAEBAQEBERAAAAAQAAEREBAAAQABAAAAAAEREAAAAQEAAAEBAAAAEAABAAAAABAAAAEAAAAAABAAAAEAAAABAQAAAAEBAQEQEQABAAEAAQABAAEAAAARAAAAABAAAAEBAAABAQABERAAAAAAEAABAAAAAAABAAAAAAEREBAAAQEAAQEBAQEREAAAABAAAAEAAAABAAEAAAAAAREQA=`;

function decodeBase64(s) {
  const bin = atob(s);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

const WC_BYTES = 336;
const FLAG_AURORA_TICKET = 1000;
const SPECIES_DEOXYS = 410;
const SETVADDRESS = 0xb8;

function buildEmeraldWonderCard(dump) {
  const wc = new Uint8Array(WC_BYTES);
  wc.set(dump.subarray(4, 4 + 332));
  wc[0] = FLAG_AURORA_TICKET & 0xff;
  wc[1] = (FLAG_AURORA_TICKET >> 8) & 0xff;
  wc[2] = SPECIES_DEOXYS & 0xff;
  wc[3] = (SPECIES_DEOXYS >> 8) & 0xff;
  wc[4] = 2004 & 0xff;
  wc[5] = (2004 >> 8) & 0xff;
  wc[6] = 0;
  wc[7] = 0;
  return wc;
}

function buildRamScript(dump) {
  const raw = dump.subarray(WC_BYTES);
  const idx = raw.indexOf(SETVADDRESS);
  const start = idx >= 0 && idx < 16 ? idx : 0;
  return raw.subarray(start);
}

const SOURCE = decodeBase64(B64);
const WC = buildEmeraldWonderCard(SOURCE);
const SCRIPT = buildRamScript(SOURCE);

export const AURORA_TICKET_PAYLOAD = new Uint8Array(WC.length + SCRIPT.length);
AURORA_TICKET_PAYLOAD.set(WC, 0);
AURORA_TICKET_PAYLOAD.set(SCRIPT, WC.length);
export const AURORA_WONDERCARD_BYTES = AURORA_TICKET_PAYLOAD.subarray(0, WC_BYTES);
export const AURORA_SCRIPT_BYTES = AURORA_TICKET_PAYLOAD.subarray(WC_BYTES);
export const AURORA_PAYLOAD_SOURCE =
  'JPAJ USA 2004 Fall card realigned for Emerald (flag 1000, Deoxys icon, setvaddress script)';
